language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --dev
  - cd vendor/gabordemooij/redbean/ && php replica.php && cd -

after_script:
  - php vendor/bin/coveralls